//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolkek.DB_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lolkekEntities : DbContext
    {
        public lolkekEntities()
            : base("name=lolkekEntities")
        {
        }
        private static lolkekEntities _context;
        public static lolkekEntities GetContext()
        {
            if (_context == null)
                _context = new lolkekEntities();
                return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TbЗаказ> TbЗаказ { get; set; }
        public virtual DbSet<TbКатегории> TbКатегории { get; set; }
        public virtual DbSet<TbПользоавтели> TbПользоавтели { get; set; }
        public virtual DbSet<TbРоли> TbРоли { get; set; }
        public virtual DbSet<TbСтатус> TbСтатус { get; set; }
        public virtual DbSet<TbТовары> TbТовары { get; set; }
    }
}
