//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolkek.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbЗаказ
    {
        public int Код_Заказа { get; set; }
        public Nullable<int> Пользователь { get; set; }
        public Nullable<int> Товар { get; set; }
        public Nullable<int> Стастус { get; set; }
    
        public virtual TbПользоавтели TbПользоавтели { get; set; }
        public virtual TbСтатус TbСтатус { get; set; }
        public virtual TbТовары TbТовары { get; set; }
    }
}
