//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolkek.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbПользоавтели
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbПользоавтели()
        {
            this.TbЗаказ = new HashSet<TbЗаказ>();
        }
    
        public int Код_Пользователся { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<int> Роль { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbЗаказ> TbЗаказ { get; set; }
        public virtual TbРоли TbРоли { get; set; }
    }
}
