//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolkek.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbТовары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbТовары()
        {
            this.TbЗаказ = new HashSet<TbЗаказ>();
        }
    
        public int Код_Товара { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public Nullable<int> Категория { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public string Путь_картинки { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbЗаказ> TbЗаказ { get; set; }
        public virtual TbКатегории TbКатегории { get; set; }
    }
}
